language: node_js

node_js:
   - "lts/*"
addons:
   chrome: stable
   apt:
      packages:
      - libgconf-2-4

cache:
   npm: true
   directories:
      - ~/.npm
      - ./node_modules
      - ~/.cache
   override:
      - npm ci
      - npm run cy:verify

install:
   - npm install cypress --save-dev
   - npm ci

script:
   - $(npm bin)/cypress run --record
